name:                stack4x4
version:             0.1.0.0
description:         Stack4x4, MiniMax and MCTS
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              https://github.com/Nick-Chapman/stack4x4.git

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- containers

default-extensions:
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NondecreasingIndentation
- NumericUnderscores
- RankNTypes
- ScopedTypeVariables

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  stack4x4.exe:
    main:                Main.hs
    source-dirs:         src
